name: ML Pipeline

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      # ---------------------------
      # Linting
      # ---------------------------
      - name: Run Pylint
        run: pylint src/train.py

      # ---------------------------
      # Unit + Integration Tests
      # ---------------------------
      - name: Run Tests
        run: pytest

      # ---------------------------
      # Train Model
      # ---------------------------
      - name: Train Model
        run: python src/train.py